export const continents: Record<string, string> = {
    AF: 'Africa',
    AN: 'Antarctica',
    AS: 'Asia',
    EU: 'Europe',
    NA: 'North America',
    OC: 'Oceania',
    SA: 'South America',
};

export type CountryData = {
    name: string;
    native: string;
    phone: number[];
    continent: string;
    continents?: string[];
    capital: string;
    currency: string[];
    languages: string[];
    memberOf?: string;
};

// ISO-3166-1 country codes with country data
export const countries: Record<string, CountryData> = {
    AD: {
        name: 'Andorra',
        native: 'Andorra',
        phone: [376],
        continent: 'EU',
        capital: 'Andorra la Vella',
        currency: ['EUR'],
        languages: ['ca'],
        memberOf: 'UN',
    },
    AE: {
        name: 'United Arab Emirates',
        native: 'دولة الإمارات العربية المتحدة',
        phone: [971],
        continent: 'AS',
        capital: 'Abu Dhabi',
        currency: ['AED'],
        languages: ['ar'],
        memberOf: 'UN',
    },
    AF: {
        name: 'Afghanistan',
        native: 'افغانستان',
        phone: [93],
        continent: 'AS',
        capital: 'Kabul',
        currency: ['AFN'],
        languages: ['ps', 'uz', 'tk'],
        memberOf: 'UN',
    },
    AG: {
        name: 'Antigua and Barbuda',
        native: 'Antigua and Barbuda',
        phone: [1268],
        continent: 'NA',
        capital: "Saint John's",
        currency: ['XCD'],
        languages: ['en'],
        memberOf: 'UN',
    },
    AI: {
        name: 'Anguilla',
        native: 'Anguilla',
        phone: [1264],
        continent: 'NA',
        capital: 'The Valley',
        currency: ['XCD'],
        languages: ['en'],
        memberOf: 'GB',
    },
    AL: {
        name: 'Albania',
        native: 'Shqipëria',
        phone: [355],
        continent: 'EU',
        capital: 'Tirana',
        currency: ['ALL'],
        languages: ['sq'],
        memberOf: 'UN',
    },
    AM: {
        name: 'Armenia',
        native: 'Հայաստան',
        phone: [374],
        continent: 'AS',
        capital: 'Yerevan',
        currency: ['AMD'],
        languages: ['hy', 'ru'],
        memberOf: 'UN',
    },
    AO: {
        name: 'Angola',
        native: 'Angola',
        phone: [244],
        continent: 'AF',
        capital: 'Luanda',
        currency: ['AOA'],
        languages: ['pt'],
        memberOf: 'UN',
    },
    AQ: {
        name: 'Antarctica',
        native: 'Antarctica',
        phone: [672],
        continent: 'AN',
        capital: '',
        currency: [],
        languages: [],
    },
    AR: {
        name: 'Argentina',
        native: 'Argentina',
        phone: [54],
        continent: 'SA',
        capital: 'Buenos Aires',
        currency: ['ARS'],
        languages: ['es', 'gn'],
        memberOf: 'UN',
    },
    AS: {
        name: 'American Samoa',
        native: 'American Samoa',
        phone: [1684],
        continent: 'OC',
        capital: 'Pago Pago',
        currency: ['USD'],
        languages: ['en', 'sm'],
        memberOf: 'US',
    },
    AT: {
        name: 'Austria',
        native: 'Österreich',
        phone: [43],
        continent: 'EU',
        capital: 'Vienna',
        currency: ['EUR'],
        languages: ['de'],
        memberOf: 'UN',
    },
    AU: {
        name: 'Australia',
        native: 'Australia',
        phone: [61],
        continent: 'OC',
        capital: 'Canberra',
        currency: ['AUD'],
        languages: ['en'],
        memberOf: 'UN',
    },
    AW: {
        name: 'Aruba',
        native: 'Aruba',
        phone: [297],
        continent: 'NA',
        capital: 'Oranjestad',
        currency: ['AWG'],
        languages: ['nl', 'pa'],
        memberOf: 'NL',
    },
    AX: {
        name: 'Aland',
        native: 'Åland',
        phone: [358],
        continent: 'EU',
        capital: 'Mariehamn',
        currency: ['EUR'],
        languages: ['sv'],
        memberOf: 'FI',
    },
    AZ: {
        name: 'Azerbaijan',
        native: 'Azərbaycan',
        phone: [994],
        continent: 'AS',
        continents: ['AS', 'EU'],
        capital: 'Baku',
        currency: ['AZN'],
        languages: ['az'],
        memberOf: 'UN',
    },
    BA: {
        name: 'Bosnia and Herzegovina',
        native: 'Bosna i Hercegovina',
        phone: [387],
        continent: 'EU',
        capital: 'Sarajevo',
        currency: ['BAM'],
        languages: ['bs', 'hr', 'sr'],
        memberOf: 'UN',
    },
    BB: {
        name: 'Barbados',
        native: 'Barbados',
        phone: [1246],
        continent: 'NA',
        capital: 'Bridgetown',
        currency: ['BBD'],
        languages: ['en'],
        memberOf: 'UN',
    },
    BD: {
        name: 'Bangladesh',
        native: 'Bangladesh',
        phone: [880],
        continent: 'AS',
        capital: 'Dhaka',
        currency: ['BDT'],
        languages: ['bn'],
        memberOf: 'UN',
    },
    BE: {
        name: 'Belgium',
        native: 'België',
        phone: [32],
        continent: 'EU',
        capital: 'Brussels',
        currency: ['EUR'],
        languages: ['nl', 'fr', 'de'],
        memberOf: 'UN',
    },
    BF: {
        name: 'Burkina Faso',
        native: 'Burkina Faso',
        phone: [226],
        continent: 'AF',
        capital: 'Ouagadougou',
        currency: ['XOF'],
        languages: ['fr', 'ff'],
        memberOf: 'UN',
    },
    BG: {
        name: 'Bulgaria',
        native: 'България',
        phone: [359],
        continent: 'EU',
        capital: 'Sofia',
        currency: ['BGN'],
        languages: ['bg'],
        memberOf: 'UN',
    },
    BH: {
        name: 'Bahrain',
        native: '‏البحرين',
        phone: [973],
        continent: 'AS',
        capital: 'Manama',
        currency: ['BHD'],
        languages: ['ar'],
        memberOf: 'UN',
    },
    BI: {
        name: 'Burundi',
        native: 'Burundi',
        phone: [257],
        continent: 'AF',
        capital: 'Bujumbura',
        currency: ['BIF'],
        languages: ['fr', 'rn'],
        memberOf: 'UN',
    },
    BJ: {
        name: 'Benin',
        native: 'Bénin',
        phone: [229],
        continent: 'AF',
        capital: 'Porto-Novo',
        currency: ['XOF'],
        languages: ['fr'],
        memberOf: 'UN',
    },
    BL: {
        name: 'Saint Barthelemy',
        native: 'Saint-Barthélemy',
        phone: [590],
        continent: 'NA',
        capital: 'Gustavia',
        currency: ['EUR'],
        languages: ['fr'],
        memberOf: 'FR',
    },
    BM: {
        name: 'Bermuda',
        native: 'Bermuda',
        phone: [1441],
        continent: 'NA',
        capital: 'Hamilton',
        currency: ['BMD'],
        languages: ['en'],
        memberOf: 'GB',
    },
    BN: {
        name: 'Brunei',
        native: 'Negara Brunei Darussalam',
        phone: [673],
        continent: 'AS',
        capital: 'Bandar Seri Begawan',
        currency: ['BND'],
        languages: ['ms'],
        memberOf: 'UN',
    },
    BO: {
        name: 'Bolivia',
        native: 'Bolivia',
        phone: [591],
        continent: 'SA',
        capital: 'Sucre',
        currency: ['BOB', 'BOV'],
        languages: ['es', 'ay', 'qu'],
        memberOf: 'UN',
    },
    BQ: {
        name: 'Bonaire',
        native: 'Bonaire',
        phone: [5997],
        continent: 'NA',
        capital: 'Kralendijk',
        currency: ['USD'],
        languages: ['nl'],
        memberOf: 'NL',
    },
    BR: {
        name: 'Brazil',
        native: 'Brasil',
        phone: [55],
        continent: 'SA',
        capital: 'Brasília',
        currency: ['BRL'],
        languages: ['pt'],
        memberOf: 'UN',
    },
    BS: {
        name: 'Bahamas',
        native: 'Bahamas',
        phone: [1242],
        continent: 'NA',
        capital: 'Nassau',
        currency: ['BSD'],
        languages: ['en'],
        memberOf: 'UN',
    },
    BT: {
        name: 'Bhutan',
        native: 'ʼbrug-yul',
        phone: [975],
        continent: 'AS',
        capital: 'Thimphu',
        currency: ['BTN', 'INR'],
        languages: ['dz'],
        memberOf: 'UN',
    },
    BV: {
        name: 'Bouvet Island',
        native: 'Bouvetøya',
        phone: [47],
        continent: 'AN',
        capital: '',
        currency: ['NOK'],
        languages: ['no', 'nb', 'nn'],
        memberOf: 'NO',
    },
    BW: {
        name: 'Botswana',
        native: 'Botswana',
        phone: [267],
        continent: 'AF',
        capital: 'Gaborone',
        currency: ['BWP'],
        languages: ['en', 'tn'],
        memberOf: 'UN',
    },
    BY: {
        name: 'Belarus',
        native: 'Белару́сь',
        phone: [375],
        continent: 'EU',
        capital: 'Minsk',
        currency: ['BYN'],
        languages: ['be', 'ru'],
        memberOf: 'UN',
    },
    BZ: {
        name: 'Belize',
        native: 'Belize',
        phone: [501],
        continent: 'NA',
        capital: 'Belmopan',
        currency: ['BZD'],
        languages: ['en', 'es'],
        memberOf: 'UN',
    },
    CA: {
        name: 'Canada',
        native: 'Canada',
        phone: [1],
        continent: 'NA',
        capital: 'Ottawa',
        currency: ['CAD'],
        languages: ['en', 'fr'],
        memberOf: 'UN',
    },
    CC: {
        name: 'Cocos (Keeling) Islands',
        native: 'Cocos (Keeling) Islands',
        phone: [61],
        continent: 'AS',
        capital: 'West Island',
        currency: ['AUD'],
        languages: ['en'],
        memberOf: 'AU',
    },
    CD: {
        name: 'Democratic Republic of the Congo',
        native: 'République démocratique du Congo',
        phone: [243],
        continent: 'AF',
        capital: 'Kinshasa',
        currency: ['CDF'],
        languages: ['fr', 'ln', 'kg', 'sw', 'lu'],
        memberOf: 'UN',
    },
    CF: {
        name: 'Central African Republic',
        native: 'Ködörösêse tî Bêafrîka',
        phone: [236],
        continent: 'AF',
        capital: 'Bangui',
        currency: ['XAF'],
        languages: ['fr', 'sg'],
        memberOf: 'UN',
    },
    CG: {
        name: 'Republic of the Congo',
        native: 'République du Congo',
        phone: [242],
        continent: 'AF',
        capital: 'Brazzaville',
        currency: ['XAF'],
        languages: ['fr', 'ln'],
        memberOf: 'UN',
    },
    CH: {
        name: 'Switzerland',
        native: 'Schweiz',
        phone: [41],
        continent: 'EU',
        capital: 'Bern',
        currency: ['CHE', 'CHF', 'CHW'],
        languages: ['de', 'fr', 'it'],
        memberOf: 'UN',
    },
    CI: {
        name: 'Ivory Coast',
        native: "Côte d'Ivoire",
        phone: [225],
        continent: 'AF',
        capital: 'Yamoussoukro',
        currency: ['XOF'],
        languages: ['fr'],
        memberOf: 'UN',
    },
    CK: {
        name: 'Cook Islands',
        native: 'Cook Islands',
        phone: [682],
        continent: 'OC',
        capital: 'Avarua',
        currency: ['NZD'],
        languages: ['en'],
        memberOf: 'NZ',
    },
    CL: {
        name: 'Chile',
        native: 'Chile',
        phone: [56],
        continent: 'SA',
        capital: 'Santiago',
        currency: ['CLF', 'CLP'],
        languages: ['es'],
        memberOf: 'UN',
    },
    CM: {
        name: 'Cameroon',
        native: 'Cameroon',
        phone: [237],
        continent: 'AF',
        capital: 'Yaoundé',
        currency: ['XAF'],
        languages: ['en', 'fr'],
        memberOf: 'UN',
    },
    CN: {
        name: 'China',
        native: '中国',
        phone: [86],
        continent: 'AS',
        capital: 'Beijing',
        currency: ['CNY'],
        languages: ['zh'],
        memberOf: 'UN',
    },
    CO: {
        name: 'Colombia',
        native: 'Colombia',
        phone: [57],
        continent: 'SA',
        capital: 'Bogotá',
        currency: ['COP'],
        languages: ['es'],
        memberOf: 'UN',
    },
    CR: {
        name: 'Costa Rica',
        native: 'Costa Rica',
        phone: [506],
        continent: 'NA',
        capital: 'San José',
        currency: ['CRC'],
        languages: ['es'],
        memberOf: 'UN',
    },
    CU: {
        name: 'Cuba',
        native: 'Cuba',
        phone: [53],
        continent: 'NA',
        capital: 'Havana',
        currency: ['CUC', 'CUP'],
        languages: ['es'],
        memberOf: 'UN',
    },
    CV: {
        name: 'Cape Verde',
        native: 'Cabo Verde',
        phone: [238],
        continent: 'AF',
        capital: 'Praia',
        currency: ['CVE'],
        languages: ['pt'],
        memberOf: 'UN',
    },
    CW: {
        name: 'Curacao',
        native: 'Curaçao',
        phone: [5999],
        continent: 'NA',
        capital: 'Willemstad',
        currency: ['ANG'],
        languages: ['nl', 'pa', 'en'],
        memberOf: 'NL',
    },
    CX: {
        name: 'Christmas Island',
        native: 'Christmas Island',
        phone: [61],
        continent: 'AS',
        capital: 'Flying Fish Cove',
        currency: ['AUD'],
        languages: ['en'],
        memberOf: 'AU',
    },
    CY: {
        name: 'Cyprus',
        native: 'Κύπρος',
        phone: [357],
        continent: 'EU',
        capital: 'Nicosia',
        currency: ['EUR'],
        languages: ['el', 'tr', 'hy'],
        memberOf: 'UN',
    },
    CZ: {
        name: 'Czech Republic',
        native: 'Česká republika',
        phone: [420],
        continent: 'EU',
        capital: 'Prague',
        currency: ['CZK'],
        languages: ['cs'],
        memberOf: 'UN',
    },
    DE: {
        name: 'Germany',
        native: 'Deutschland',
        phone: [49],
        continent: 'EU',
        capital: 'Berlin',
        currency: ['EUR'],
        languages: ['de'],
        memberOf: 'UN',
    },
    DJ: {
        name: 'Djibouti',
        native: 'Djibouti',
        phone: [253],
        continent: 'AF',
        capital: 'Djibouti',
        currency: ['DJF'],
        languages: ['fr', 'ar'],
        memberOf: 'UN',
    },
    DK: {
        name: 'Denmark',
        native: 'Danmark',
        phone: [45],
        continent: 'EU',
        continents: ['EU', 'NA'],
        capital: 'Copenhagen',
        currency: ['DKK'],
        languages: ['da'],
        memberOf: 'UN',
    },
    DM: {
        name: 'Dominica',
        native: 'Dominica',
        phone: [1767],
        continent: 'NA',
        capital: 'Roseau',
        currency: ['XCD'],
        languages: ['en'],
        memberOf: 'UN',
    },
    DO: {
        name: 'Dominican Republic',
        native: 'República Dominicana',
        phone: [1809, 1829, 1849],
        continent: 'NA',
        capital: 'Santo Domingo',
        currency: ['DOP'],
        languages: ['es'],
        memberOf: 'UN',
    },
    DZ: {
        name: 'Algeria',
        native: 'الجزائر',
        phone: [213],
        continent: 'AF',
        capital: 'Algiers',
        currency: ['DZD'],
        languages: ['ar'],
        memberOf: 'UN',
    },
    EC: {
        name: 'Ecuador',
        native: 'Ecuador',
        phone: [593],
        continent: 'SA',
        capital: 'Quito',
        currency: ['USD'],
        languages: ['es'],
        memberOf: 'UN',
    },
    EE: {
        name: 'Estonia',
        native: 'Eesti',
        phone: [372],
        continent: 'EU',
        capital: 'Tallinn',
        currency: ['EUR'],
        languages: ['et'],
        memberOf: 'UN',
    },
    EG: {
        name: 'Egypt',
        native: 'مصر‎',
        phone: [20],
        continent: 'AF',
        continents: ['AF', 'AS'],
        capital: 'Cairo',
        currency: ['EGP'],
        languages: ['ar'],
        memberOf: 'UN',
    },
    EH: {
        name: 'Western Sahara',
        native: 'الصحراء الغربية',
        phone: [212],
        continent: 'AF',
        capital: 'El Aaiún',
        currency: ['MAD', 'DZD', 'MRU'],
        languages: ['es'],
    },
    ER: {
        name: 'Eritrea',
        native: 'ኤርትራ',
        phone: [291],
        continent: 'AF',
        capital: 'Asmara',
        currency: ['ERN'],
        languages: ['ti', 'ar', 'en'],

        memberOf: 'UN',
    },
    ES: {
        name: 'Spain',
        native: 'España',
        phone: [34],
        continent: 'EU',
        capital: 'Madrid',
        currency: ['EUR'],
        languages: ['es', 'eu', 'ca', 'gl', 'oc'],
        memberOf: 'UN',
    },
    ET: {
        name: 'Ethiopia',
        native: 'ኢትዮጵያ',
        phone: [251],
        continent: 'AF',
        capital: 'Addis Ababa',
        currency: ['ETB'],
        languages: ['am'],
        memberOf: 'UN',
    },
    FI: {
        name: 'Finland',
        native: 'Suomi',
        phone: [358],
        continent: 'EU',
        capital: 'Helsinki',
        currency: ['EUR'],
        languages: ['fi', 'sv'],
        memberOf: 'UN',
    },
    FJ: {
        name: 'Fiji',
        native: 'Fiji',
        phone: [679],
        continent: 'OC',
        capital: 'Suva',
        currency: ['FJD'],
        languages: ['en', 'fj', 'hi', 'ur'],
        memberOf: 'UN',
    },
    FK: {
        name: 'Falkland Islands',
        native: 'Falkland Islands',
        phone: [500],
        continent: 'SA',
        capital: 'Stanley',
        currency: ['FKP'],
        languages: ['en'],
        memberOf: 'GB',
    },
    FM: {
        name: 'Micronesia',
        native: 'Micronesia',
        phone: [691],
        continent: 'OC',
        capital: 'Palikir',
        currency: ['USD'],
        languages: ['en'],
        memberOf: 'UN',
    },
    FO: {
        name: 'Faroe Islands',
        native: 'Føroyar',
        phone: [298],
        continent: 'EU',
        capital: 'Tórshavn',
        currency: ['DKK'],
        languages: ['fo'],
        memberOf: 'DK',
    },
    FR: {
        name: 'France',
        native: 'France',
        phone: [33],
        continent: 'EU',
        capital: 'Paris',
        currency: ['EUR'],
        languages: ['fr'],
        memberOf: 'UN',
    },
    GA: {
        name: 'Gabon',
        native: 'Gabon',
        phone: [241],
        continent: 'AF',
        capital: 'Libreville',
        currency: ['XAF'],
        languages: ['fr'],
        memberOf: 'UN',
    },
    GB: {
        name: 'United Kingdom',
        native: 'United Kingdom',
        phone: [44],
        continent: 'EU',
        capital: 'London',
        currency: ['GBP'],
        languages: ['en'],
        memberOf: 'UN',
    },
    GD: {
        name: 'Grenada',
        native: 'Grenada',
        phone: [1473],
        continent: 'NA',
        capital: "St. George's",
        currency: ['XCD'],
        languages: ['en'],
        memberOf: 'UN',
    },
    GE: {
        name: 'Georgia',
        native: 'საქართველო',
        phone: [995],
        continent: 'AS',
        continents: ['AS', 'EU'],
        capital: 'Tbilisi',
        currency: ['GEL'],
        languages: ['ka'],
        memberOf: 'UN',
    },
    GF: {
        name: 'French Guiana',
        native: 'Guyane française',
        phone: [594],
        continent: 'SA',
        capital: 'Cayenne',
        currency: ['EUR'],
        languages: ['fr'],
        memberOf: 'FR',
    },
    GG: {
        name: 'Guernsey',
        native: 'Guernsey',
        phone: [44],
        continent: 'EU',
        capital: 'St. Peter Port',
        currency: ['GBP'],
        languages: ['en', 'fr'],
        memberOf: 'GB',
    },
    GH: {
        name: 'Ghana',
        native: 'Ghana',
        phone: [233],
        continent: 'AF',
        capital: 'Accra',
        currency: ['GHS'],
        languages: ['en'],
        memberOf: 'UN',
    },
    GI: {
        name: 'Gibraltar',
        native: 'Gibraltar',
        phone: [350],
        continent: 'EU',
        capital: 'Gibraltar',
        currency: ['GIP'],
        languages: ['en'],
        memberOf: 'GB',
    },
    GL: {
        name: 'Greenland',
        native: 'Kalaallit Nunaat',
        phone: [299],
        continent: 'NA',
        capital: 'Nuuk',
        currency: ['DKK'],
        languages: ['kl'],
        memberOf: 'DK',
    },
    GM: {
        name: 'Gambia',
        native: 'Gambia',
        phone: [220],
        continent: 'AF',
        capital: 'Banjul',
        currency: ['GMD'],
        languages: ['en'],
        memberOf: 'UN',
    },
    GN: {
        name: 'Guinea',
        native: 'Guinée',
        phone: [224],
        continent: 'AF',
        capital: 'Conakry',
        currency: ['GNF'],
        languages: ['fr', 'ff'],
        memberOf: 'UN',
    },
    GP: {
        name: 'Guadeloupe',
        native: 'Guadeloupe',
        phone: [590],
        continent: 'NA',
        capital: 'Basse-Terre',
        currency: ['EUR'],
        languages: ['fr'],
        memberOf: 'FR',
    },
    GQ: {
        name: 'Equatorial Guinea',
        native: 'Guinea Ecuatorial',
        phone: [240],
        continent: 'AF',
        capital: 'Malabo',
        currency: ['XAF'],
        languages: ['es', 'fr'],
        memberOf: 'UN',
    },
    GR: {
        name: 'Greece',
        native: 'Ελλάδα',
        phone: [30],
        continent: 'EU',
        capital: 'Athens',
        currency: ['EUR'],
        languages: ['el'],
        memberOf: 'UN',
    },
    GS: {
        name: 'South Georgia and the South Sandwich Islands',
        native: 'South Georgia',
        phone: [500],
        continent: 'AN',
        capital: 'King Edward Point',
        currency: ['GBP'],
        languages: ['en'],
        memberOf: 'GB',
    },
    GT: {
        name: 'Guatemala',
        native: 'Guatemala',
        phone: [502],
        continent: 'NA',
        capital: 'Guatemala City',
        currency: ['GTQ'],
        languages: ['es'],
        memberOf: 'UN',
    },
    GU: {
        name: 'Guam',
        native: 'Guam',
        phone: [1671],
        continent: 'OC',
        capital: 'Hagåtña',
        currency: ['USD'],
        languages: ['en', 'ch', 'es'],
        memberOf: 'US',
    },
    GW: {
        name: 'Guinea-Bissau',
        native: 'Guiné-Bissau',
        phone: [245],
        continent: 'AF',
        capital: 'Bissau',
        currency: ['XOF'],
        languages: ['pt'],
        memberOf: 'UN',
    },
    GY: {
        name: 'Guyana',
        native: 'Guyana',
        phone: [592],
        continent: 'SA',
        capital: 'Georgetown',
        currency: ['GYD'],
        languages: ['en'],
        memberOf: 'UN',
    },
    HK: {
        name: 'Hong Kong',
        native: '香港',
        phone: [852],
        continent: 'AS',
        capital: 'City of Victoria',
        currency: ['HKD'],
        languages: ['zh', 'en'],
        memberOf: 'CN',
    },
    HM: {
        name: 'Heard Island and McDonald Islands',
        native: 'Heard Island and McDonald Islands',
        phone: [61],
        continent: 'AN',
        capital: '',
        currency: ['AUD'],
        languages: ['en'],
        memberOf: 'AU',
    },
    HN: {
        name: 'Honduras',
        native: 'Honduras',
        phone: [504],
        continent: 'NA',
        capital: 'Tegucigalpa',
        currency: ['HNL'],
        languages: ['es'],
        memberOf: 'UN',
    },
    HR: {
        name: 'Croatia',
        native: 'Hrvatska',
        phone: [385],
        continent: 'EU',
        capital: 'Zagreb',
        currency: ['EUR'],
        languages: ['hr'],
        memberOf: 'UN',
    },
    HT: {
        name: 'Haiti',
        native: 'Haïti',
        phone: [509],
        continent: 'NA',
        capital: 'Port-au-Prince',
        currency: ['HTG', 'USD'],
        languages: ['fr', 'ht'],
        memberOf: 'UN',
    },
    HU: {
        name: 'Hungary',
        native: 'Magyarország',
        phone: [36],
        continent: 'EU',
        capital: 'Budapest',
        currency: ['HUF'],
        languages: ['hu'],
        memberOf: 'UN',
    },
    ID: {
        name: 'Indonesia',
        native: 'Indonesia',
        phone: [62],
        continent: 'AS',
        capital: 'Jakarta',
        currency: ['IDR'],
        languages: ['id'],
        memberOf: 'UN',
    },
    IE: {
        name: 'Ireland',
        native: 'Éire',
        phone: [353],
        continent: 'EU',
        capital: 'Dublin',
        currency: ['EUR'],
        languages: ['ga', 'en'],
        memberOf: 'UN',
    },
    IL: {
        name: 'Israel',
        native: 'יִשְׂרָאֵל',
        phone: [972],
        continent: 'AS',
        capital: 'Jerusalem',
        currency: ['ILS'],
        languages: ['he', 'ar'],
        memberOf: 'UN',
    },
    IM: {
        name: 'Isle of Man',
        native: 'Isle of Man',
        phone: [44],
        continent: 'EU',
        capital: 'Douglas',
        currency: ['GBP'],
        languages: ['en', 'gv'],
        memberOf: 'GB',
    },
    IN: {
        name: 'India',
        native: 'भारत',
        phone: [91],
        continent: 'AS',
        capital: 'New Delhi',
        currency: ['INR'],
        languages: ['hi', 'en'],
        memberOf: 'UN',
    },
    IO: {
        name: 'British Indian Ocean Territory',
        native: 'British Indian Ocean Territory',
        phone: [246],
        continent: 'AS',
        capital: 'Diego Garcia',
        currency: ['USD'],
        languages: ['en'],
        memberOf: 'GB',
    },
    IQ: {
        name: 'Iraq',
        native: 'العراق',
        phone: [964],
        continent: 'AS',
        capital: 'Baghdad',
        currency: ['IQD'],
        languages: ['ar', 'ku'],
        memberOf: 'UN',
    },
    IR: {
        name: 'Iran',
        native: 'ایران',
        phone: [98],
        continent: 'AS',
        capital: 'Tehran',
        currency: ['IRR'],
        languages: ['fa'],
        memberOf: 'UN',
    },
    IS: {
        name: 'Iceland',
        native: 'Ísland',
        phone: [354],
        continent: 'EU',
        capital: 'Reykjavik',
        currency: ['ISK'],
        languages: ['is'],
        memberOf: 'UN',
    },
    IT: {
        name: 'Italy',
        native: 'Italia',
        phone: [39],
        continent: 'EU',
        capital: 'Rome',
        currency: ['EUR'],
        languages: ['it'],
        memberOf: 'UN',
    },
    JE: {
        name: 'Jersey',
        native: 'Jersey',
        phone: [44],
        continent: 'EU',
        capital: 'Saint Helier',
        currency: ['GBP'],
        languages: ['en', 'fr'],
        memberOf: 'GB',
    },
    JM: {
        name: 'Jamaica',
        native: 'Jamaica',
        phone: [1876],
        continent: 'NA',
        capital: 'Kingston',
        currency: ['JMD'],
        languages: ['en'],
        memberOf: 'UN',
    },
    JO: {
        name: 'Jordan',
        native: 'الأردن',
        phone: [962],
        continent: 'AS',
        capital: 'Amman',
        currency: ['JOD'],
        languages: ['ar'],
        memberOf: 'UN',
    },
    JP: {
        name: 'Japan',
        native: '日本',
        phone: [81],
        continent: 'AS',
        capital: 'Tokyo',
        currency: ['JPY'],
        languages: ['ja'],
        memberOf: 'UN',
    },
    KE: {
        name: 'Kenya',
        native: 'Kenya',
        phone: [254],
        continent: 'AF',
        capital: 'Nairobi',
        currency: ['KES'],
        languages: ['en', 'sw'],
        memberOf: 'UN',
    },
    KG: {
        name: 'Kyrgyzstan',
        native: 'Кыргызстан',
        phone: [996],
        continent: 'AS',
        capital: 'Bishkek',
        currency: ['KGS'],
        languages: ['ky', 'ru'],
        memberOf: 'UN',
    },
    KH: {
        name: 'Cambodia',
        native: 'Kâmpŭchéa',
        phone: [855],
        continent: 'AS',
        capital: 'Phnom Penh',
        currency: ['KHR'],
        languages: ['km'],
        memberOf: 'UN',
    },
    KI: {
        name: 'Kiribati',
        native: 'Kiribati',
        phone: [686],
        continent: 'OC',
        capital: 'South Tarawa',
        currency: ['AUD'],
        languages: ['en'],
        memberOf: 'UN',
    },
    KM: {
        name: 'Comoros',
        native: 'Komori',
        phone: [269],
        continent: 'AF',
        capital: 'Moroni',
        currency: ['KMF'],
        languages: ['ar', 'fr'],
        memberOf: 'UN',
    },
    KN: {
        name: 'Saint Kitts and Nevis',
        native: 'Saint Kitts and Nevis',
        phone: [1869],
        continent: 'NA',
        capital: 'Basseterre',
        currency: ['XCD'],
        languages: ['en'],
        memberOf: 'UN',
    },
    KP: {
        name: 'North Korea',
        native: '북한',
        phone: [850],
        continent: 'AS',
        capital: 'Pyongyang',
        currency: ['KPW'],
        languages: ['ko'],
        memberOf: 'UN',
    },
    KR: {
        name: 'South Korea',
        native: '대한민국',
        phone: [82],
        continent: 'AS',
        capital: 'Seoul',
        currency: ['KRW'],
        languages: ['ko'],
        memberOf: 'UN',
    },
    KW: {
        name: 'Kuwait',
        native: 'الكويت',
        phone: [965],
        continent: 'AS',
        capital: 'Kuwait City',
        currency: ['KWD'],
        languages: ['ar'],
        memberOf: 'UN',
    },
    KY: {
        name: 'Cayman Islands',
        native: 'Cayman Islands',
        phone: [1345],
        continent: 'NA',
        capital: 'George Town',
        currency: ['KYD'],
        languages: ['en'],
        memberOf: 'GB',
    },
    KZ: {
        name: 'Kazakhstan',
        native: 'Қазақстан',
        phone: [76, 77],
        continent: 'AS',
        continents: ['AS', 'EU'],
        capital: 'Astana',
        currency: ['KZT'],
        languages: ['kk', 'ru'],
        memberOf: 'UN',
    },
    LA: {
        name: 'Laos',
        native: 'ສປປລາວ',
        phone: [856],
        continent: 'AS',
        capital: 'Vientiane',
        currency: ['LAK'],
        languages: ['lo'],
        memberOf: 'UN',
    },
    LB: {
        name: 'Lebanon',
        native: 'لبنان',
        phone: [961],
        continent: 'AS',
        capital: 'Beirut',
        currency: ['LBP'],
        languages: ['ar', 'fr'],
        memberOf: 'UN',
    },
    LC: {
        name: 'Saint Lucia',
        native: 'Saint Lucia',
        phone: [1758],
        continent: 'NA',
        capital: 'Castries',
        currency: ['XCD'],
        languages: ['en'],
        memberOf: 'UN',
    },
    LI: {
        name: 'Liechtenstein',
        native: 'Liechtenstein',
        phone: [423],
        continent: 'EU',
        capital: 'Vaduz',
        currency: ['CHF'],
        languages: ['de'],
        memberOf: 'UN',
    },
    LK: {
        name: 'Sri Lanka',
        native: 'śrī laṃkāva',
        phone: [94],
        continent: 'AS',
        capital: 'Colombo',
        currency: ['LKR'],
        languages: ['si', 'ta'],
        memberOf: 'UN',
    },
    LR: {
        name: 'Liberia',
        native: 'Liberia',
        phone: [231],
        continent: 'AF',
        capital: 'Monrovia',
        currency: ['LRD'],
        languages: ['en'],
        memberOf: 'UN',
    },
    LS: {
        name: 'Lesotho',
        native: 'Lesotho',
        phone: [266],
        continent: 'AF',
        capital: 'Maseru',
        currency: ['LSL', 'ZAR'],
        languages: ['en', 'st'],
        memberOf: 'UN',
    },
    LT: {
        name: 'Lithuania',
        native: 'Lietuva',
        phone: [370],
        continent: 'EU',
        capital: 'Vilnius',
        currency: ['EUR'],
        languages: ['lt'],
        memberOf: 'UN',
    },
    LU: {
        name: 'Luxembourg',
        native: 'Luxembourg',
        phone: [352],
        continent: 'EU',
        capital: 'Luxembourg',
        currency: ['EUR'],
        languages: ['fr', 'de', 'lb'],
        memberOf: 'UN',
    },
    LV: {
        name: 'Latvia',
        native: 'Latvija',
        phone: [371],
        continent: 'EU',
        capital: 'Riga',
        currency: ['EUR'],
        languages: ['lv'],
        memberOf: 'UN',
    },
    LY: {
        name: 'Libya',
        native: '‏ليبيا',
        phone: [218],
        continent: 'AF',
        capital: 'Tripoli',
        currency: ['LYD'],
        languages: ['ar'],
        memberOf: 'UN',
    },
    MA: {
        name: 'Morocco',
        native: 'المغرب',
        phone: [212],
        continent: 'AF',
        capital: 'Rabat',
        currency: ['MAD'],
        languages: ['ar'],
        memberOf: 'UN',
    },
    MC: {
        name: 'Monaco',
        native: 'Monaco',
        phone: [377],
        continent: 'EU',
        capital: 'Monaco',
        currency: ['EUR'],
        languages: ['fr'],
        memberOf: 'UN',
    },
    MD: {
        name: 'Moldova',
        native: 'Moldova',
        phone: [373],
        continent: 'EU',
        capital: 'Chișinău',
        currency: ['MDL'],
        languages: ['ro'],
        memberOf: 'UN',
    },
    ME: {
        name: 'Montenegro',
        native: 'Црна Гора',
        phone: [382],
        continent: 'EU',
        capital: 'Podgorica',
        currency: ['EUR'],
        languages: ['sr', 'bs', 'sq', 'hr'],
        memberOf: 'UN',
    },
    MF: {
        name: 'Saint Martin',
        native: 'Saint-Martin',
        phone: [590],
        continent: 'NA',
        capital: 'Marigot',
        currency: ['EUR'],
        languages: ['en', 'fr', 'nl'],
        memberOf: 'FR',
    },
    MG: {
        name: 'Madagascar',
        native: 'Madagasikara',
        phone: [261],
        continent: 'AF',
        capital: 'Antananarivo',
        currency: ['MGA'],
        languages: ['fr', 'mg'],
        memberOf: 'UN',
    },
    MH: {
        name: 'Marshall Islands',
        native: 'M̧ajeļ',
        phone: [692],
        continent: 'OC',
        capital: 'Majuro',
        currency: ['USD'],
        languages: ['en', 'mh'],
        memberOf: 'UN',
    },
    MK: {
        name: 'North Macedonia',
        native: 'Северна Македонија',
        phone: [389],
        continent: 'EU',
        capital: 'Skopje',
        currency: ['MKD'],
        languages: ['mk'],
        memberOf: 'UN',
    },
    ML: {
        name: 'Mali',
        native: 'Mali',
        phone: [223],
        continent: 'AF',
        capital: 'Bamako',
        currency: ['XOF'],
        languages: ['fr'],
        memberOf: 'UN',
    },
    MM: {
        name: 'Myanmar (Burma)',
        native: 'မြန်မာ',
        phone: [95],
        continent: 'AS',
        capital: 'Naypyidaw',
        currency: ['MMK'],
        languages: ['my'],
        memberOf: 'UN',
    },
    MN: {
        name: 'Mongolia',
        native: 'Монгол улс',
        phone: [976],
        continent: 'AS',
        capital: 'Ulan Bator',
        currency: ['MNT'],
        languages: ['mn'],
        memberOf: 'UN',
    },
    MO: {
        name: 'Macao',
        native: '澳門',
        phone: [853],
        continent: 'AS',
        capital: '',
        currency: ['MOP'],
        languages: ['zh', 'pt'],
        memberOf: 'CN',
    },
    MP: {
        name: 'Northern Mariana Islands',
        native: 'Northern Mariana Islands',
        phone: [1670],
        continent: 'OC',
        capital: 'Saipan',
        currency: ['USD'],
        languages: ['en', 'ch'],
        memberOf: 'US',
    },
    MQ: {
        name: 'Martinique',
        native: 'Martinique',
        phone: [596],
        continent: 'NA',
        capital: 'Fort-de-France',
        currency: ['EUR'],
        languages: ['fr'],
        memberOf: 'FR',
    },
    MR: {
        name: 'Mauritania',
        native: 'موريتانيا',
        phone: [222],
        continent: 'AF',
        capital: 'Nouakchott',
        currency: ['MRU'],
        languages: ['ar'],
        memberOf: 'UN',
    },
    MS: {
        name: 'Montserrat',
        native: 'Montserrat',
        phone: [1664],
        continent: 'NA',
        capital: 'Plymouth',
        currency: ['XCD'],
        languages: ['en'],
        memberOf: 'GB',
    },
    MT: {
        name: 'Malta',
        native: 'Malta',
        phone: [356],
        continent: 'EU',
        capital: 'Valletta',
        currency: ['EUR'],
        languages: ['mt', 'en'],
        memberOf: 'UN',
    },
    MU: {
        name: 'Mauritius',
        native: 'Maurice',
        phone: [230],
        continent: 'AF',
        capital: 'Port Louis',
        currency: ['MUR'],
        languages: ['en'],
        memberOf: 'UN',
    },
    MV: {
        name: 'Maldives',
        native: 'Maldives',
        phone: [960],
        continent: 'AS',
        capital: 'Malé',
        currency: ['MVR'],
        languages: ['dv'],
        memberOf: 'UN',
    },
    MW: {
        name: 'Malawi',
        native: 'Malawi',
        phone: [265],
        continent: 'AF',
        capital: 'Lilongwe',
        currency: ['MWK'],
        languages: ['en', 'ny'],
        memberOf: 'UN',
    },
    MX: {
        name: 'Mexico',
        native: 'México',
        phone: [52],
        continent: 'NA',
        capital: 'Mexico City',
        currency: ['MXN'],
        languages: ['es'],
        memberOf: 'UN',
    },
    MY: {
        name: 'Malaysia',
        native: 'Malaysia',
        phone: [60],
        continent: 'AS',
        capital: 'Kuala Lumpur',
        currency: ['MYR'],
        languages: ['ms'],
        memberOf: 'UN',
    },
    MZ: {
        name: 'Mozambique',
        native: 'Moçambique',
        phone: [258],
        continent: 'AF',
        capital: 'Maputo',
        currency: ['MZN'],
        languages: ['pt'],
        memberOf: 'UN',
    },
    NA: {
        name: 'Namibia',
        native: 'Namibia',
        phone: [264],
        continent: 'AF',
        capital: 'Windhoek',
        currency: ['NAD', 'ZAR'],
        languages: ['en', 'af'],
        memberOf: 'UN',
    },
    NC: {
        name: 'New Caledonia',
        native: 'Nouvelle-Calédonie',
        phone: [687],
        continent: 'OC',
        capital: 'Nouméa',
        currency: ['XPF'],
        languages: ['fr'],
        memberOf: 'FR',
    },
    NE: {
        name: 'Niger',
        native: 'Niger',
        phone: [227],
        continent: 'AF',
        capital: 'Niamey',
        currency: ['XOF'],
        languages: ['fr'],
        memberOf: 'UN',
    },
    NF: {
        name: 'Norfolk Island',
        native: 'Norfolk Island',
        phone: [672],
        continent: 'OC',
        capital: 'Kingston',
        currency: ['AUD'],
        languages: ['en'],
        memberOf: 'AU',
    },
    NG: {
        name: 'Nigeria',
        native: 'Nigeria',
        phone: [234],
        continent: 'AF',
        capital: 'Abuja',
        currency: ['NGN'],
        languages: ['en'],
        memberOf: 'UN',
    },
    NI: {
        name: 'Nicaragua',
        native: 'Nicaragua',
        phone: [505],
        continent: 'NA',
        capital: 'Managua',
        currency: ['NIO'],
        languages: ['es'],
        memberOf: 'UN',
    },
    NL: {
        name: 'Netherlands',
        native: 'Nederland',
        phone: [31],
        continent: 'EU',
        capital: 'Amsterdam',
        currency: ['EUR'],
        languages: ['nl'],
        memberOf: 'UN',
    },
    NO: {
        name: 'Norway',
        native: 'Norge',
        phone: [47],
        continent: 'EU',
        capital: 'Oslo',
        currency: ['NOK'],
        languages: ['no', 'nb', 'nn'],
        memberOf: 'UN',
    },
    NP: {
        name: 'Nepal',
        native: 'नेपाल',
        phone: [977],
        continent: 'AS',
        capital: 'Kathmandu',
        currency: ['NPR'],
        languages: ['ne'],
        memberOf: 'UN',
    },
    NR: {
        name: 'Nauru',
        native: 'Nauru',
        phone: [674],
        continent: 'OC',
        capital: 'Yaren',
        currency: ['AUD'],
        languages: ['en', 'na'],
        memberOf: 'UN',
    },
    NU: {
        name: 'Niue',
        native: 'Niuē',
        phone: [683],
        continent: 'OC',
        capital: 'Alofi',
        currency: ['NZD'],
        languages: ['en'],
        memberOf: 'NZ',
    },
    NZ: {
        name: 'New Zealand',
        native: 'New Zealand',
        phone: [64],
        continent: 'OC',
        capital: 'Wellington',
        currency: ['NZD'],
        languages: ['en', 'mi'],
        memberOf: 'UN',
    },
    OM: {
        name: 'Oman',
        native: 'عمان',
        phone: [968],
        continent: 'AS',
        capital: 'Muscat',
        currency: ['OMR'],
        languages: ['ar'],
        memberOf: 'UN',
    },
    PA: {
        name: 'Panama',
        native: 'Panamá',
        phone: [507],
        continent: 'NA',
        capital: 'Panama City',
        currency: ['PAB', 'USD'],
        languages: ['es'],
        memberOf: 'UN',
    },
    PE: {
        name: 'Peru',
        native: 'Perú',
        phone: [51],
        continent: 'SA',
        capital: 'Lima',
        currency: ['PEN'],
        languages: ['es'],
        memberOf: 'UN',
    },
    PF: {
        name: 'French Polynesia',
        native: 'Polynésie française',
        phone: [689],
        continent: 'OC',
        capital: 'Papeetē',
        currency: ['XPF'],
        languages: ['fr'],
        memberOf: 'FR',
    },
    PG: {
        name: 'Papua New Guinea',
        native: 'Papua Niugini',
        phone: [675],
        continent: 'OC',
        capital: 'Port Moresby',
        currency: ['PGK'],
        languages: ['en'],
        memberOf: 'UN',
    },
    PH: {
        name: 'Philippines',
        native: 'Pilipinas',
        phone: [63],
        continent: 'AS',
        capital: 'Manila',
        currency: ['PHP'],
        languages: ['en'],
        memberOf: 'UN',
    },
    PK: {
        name: 'Pakistan',
        native: 'Pakistan',
        phone: [92],
        continent: 'AS',
        capital: 'Islamabad',
        currency: ['PKR'],
        languages: ['en', 'ur'],
        memberOf: 'UN',
    },
    PL: {
        name: 'Poland',
        native: 'Polska',
        phone: [48],
        continent: 'EU',
        capital: 'Warsaw',
        currency: ['PLN'],
        languages: ['pl'],
        memberOf: 'UN',
    },
    PM: {
        name: 'Saint Pierre and Miquelon',
        native: 'Saint-Pierre-et-Miquelon',
        phone: [508],
        continent: 'NA',
        capital: 'Saint-Pierre',
        currency: ['EUR'],
        languages: ['fr'],
        memberOf: 'FR',
    },
    PN: {
        name: 'Pitcairn Islands',
        native: 'Pitcairn Islands',
        phone: [64],
        continent: 'OC',
        capital: 'Adamstown',
        currency: ['NZD'],
        languages: ['en'],
        memberOf: 'GB',
    },
    PR: {
        name: 'Puerto Rico',
        native: 'Puerto Rico',
        phone: [1787, 1939],
        continent: 'NA',
        capital: 'San Juan',
        currency: ['USD'],
        languages: ['es', 'en'],
        memberOf: 'US',
    },
    PS: {
        name: 'Palestine',
        native: 'فلسطين',
        phone: [970],
        continent: 'AS',
        capital: 'Ramallah',
        currency: ['ILS'],
        languages: ['ar'],
    },
    PT: {
        name: 'Portugal',
        native: 'Portugal',
        phone: [351],
        continent: 'EU',
        capital: 'Lisbon',
        currency: ['EUR'],
        languages: ['pt'],
        memberOf: 'UN',
    },
    PW: {
        name: 'Palau',
        native: 'Palau',
        phone: [680],
        continent: 'OC',
        capital: 'Ngerulmud',
        currency: ['USD'],
        languages: ['en'],
        memberOf: 'UN',
    },
    PY: {
        name: 'Paraguay',
        native: 'Paraguay',
        phone: [595],
        continent: 'SA',
        capital: 'Asunción',
        currency: ['PYG'],
        languages: ['es', 'gn'],
        memberOf: 'UN',
    },
    QA: {
        name: 'Qatar',
        native: 'قطر',
        phone: [974],
        continent: 'AS',
        capital: 'Doha',
        currency: ['QAR'],
        languages: ['ar'],
        memberOf: 'UN',
    },
    RE: {
        name: 'Reunion',
        native: 'La Réunion',
        phone: [262],
        continent: 'AF',
        capital: 'Saint-Denis',
        currency: ['EUR'],
        languages: ['fr'],
        memberOf: 'FR',
    },
    RO: {
        name: 'Romania',
        native: 'România',
        phone: [40],
        continent: 'EU',
        capital: 'Bucharest',
        currency: ['RON'],
        languages: ['ro'],
        memberOf: 'UN',
    },
    RS: {
        name: 'Serbia',
        native: 'Србија',
        phone: [381],
        continent: 'EU',
        capital: 'Belgrade',
        currency: ['RSD'],
        languages: ['sr'],
        memberOf: 'UN',
    },
    RU: {
        name: 'Russia',
        native: 'Россия',
        phone: [7],
        continent: 'AS',
        continents: ['AS', 'EU'],
        capital: 'Moscow',
        currency: ['RUB'],
        languages: ['ru'],
        memberOf: 'UN',
    },
    RW: {
        name: 'Rwanda',
        native: 'Rwanda',
        phone: [250],
        continent: 'AF',
        capital: 'Kigali',
        currency: ['RWF'],
        languages: ['rw', 'en', 'fr'],
        memberOf: 'UN',
    },
    SA: {
        name: 'Saudi Arabia',
        native: 'العربية السعودية',
        phone: [966],
        continent: 'AS',
        capital: 'Riyadh',
        currency: ['SAR'],
        languages: ['ar'],
        memberOf: 'UN',
    },
    SB: {
        name: 'Solomon Islands',
        native: 'Solomon Islands',
        phone: [677],
        continent: 'OC',
        capital: 'Honiara',
        currency: ['SBD'],
        languages: ['en'],
        memberOf: 'UN',
    },
    SC: {
        name: 'Seychelles',
        native: 'Seychelles',
        phone: [248],
        continent: 'AF',
        capital: 'Victoria',
        currency: ['SCR'],
        languages: ['fr', 'en'],
        memberOf: 'UN',
    },
    SD: {
        name: 'Sudan',
        native: 'السودان',
        phone: [249],
        continent: 'AF',
        capital: 'Khartoum',
        currency: ['SDG'],
        languages: ['ar', 'en'],
        memberOf: 'UN',
    },
    SE: {
        name: 'Sweden',
        native: 'Sverige',
        phone: [46],
        continent: 'EU',
        capital: 'Stockholm',
        currency: ['SEK'],
        languages: ['sv'],
        memberOf: 'UN',
    },
    SG: {
        name: 'Singapore',
        native: 'Singapore',
        phone: [65],
        continent: 'AS',
        capital: 'Singapore',
        currency: ['SGD'],
        languages: ['en', 'ms', 'ta', 'zh'],
        memberOf: 'UN',
    },
    SH: {
        name: 'Saint Helena',
        native: 'Saint Helena',
        phone: [290],
        continent: 'AF',
        capital: 'Jamestown',
        currency: ['SHP'],
        languages: ['en'],
        memberOf: 'GB',
    },
    SI: {
        name: 'Slovenia',
        native: 'Slovenija',
        phone: [386],
        continent: 'EU',
        capital: 'Ljubljana',
        currency: ['EUR'],
        languages: ['sl'],
        memberOf: 'UN',
    },
    SJ: {
        name: 'Svalbard and Jan Mayen',
        native: 'Svalbard og Jan Mayen',
        phone: [4779],
        continent: 'EU',
        capital: 'Longyearbyen',
        currency: ['NOK'],
        languages: ['no'],
        memberOf: 'NO',
    },
    SK: {
        name: 'Slovakia',
        native: 'Slovensko',
        phone: [421],
        continent: 'EU',
        capital: 'Bratislava',
        currency: ['EUR'],
        languages: ['sk'],
        memberOf: 'UN',
    },
    SL: {
        name: 'Sierra Leone',
        native: 'Sierra Leone',
        phone: [232],
        continent: 'AF',
        capital: 'Freetown',
        currency: ['SLL'],
        languages: ['en'],
        memberOf: 'UN',
    },
    SM: {
        name: 'San Marino',
        native: 'San Marino',
        phone: [378],
        continent: 'EU',
        capital: 'City of San Marino',
        currency: ['EUR'],
        languages: ['it'],
        memberOf: 'UN',
    },
    SN: {
        name: 'Senegal',
        native: 'Sénégal',
        phone: [221],
        continent: 'AF',
        capital: 'Dakar',
        currency: ['XOF'],
        languages: ['fr'],
        memberOf: 'UN',
    },
    SO: {
        name: 'Somalia',
        native: 'Soomaaliya',
        phone: [252],
        continent: 'AF',
        capital: 'Mogadishu',
        currency: ['SOS'],
        languages: ['so', 'ar'],
        memberOf: 'UN',
    },
    SR: {
        name: 'Suriname',
        native: 'Suriname',
        phone: [597],
        continent: 'SA',
        capital: 'Paramaribo',
        currency: ['SRD'],
        languages: ['nl'],
        memberOf: 'UN',
    },
    SS: {
        name: 'South Sudan',
        native: 'South Sudan',
        phone: [211],
        continent: 'AF',
        capital: 'Juba',
        currency: ['SSP'],
        languages: ['en'],
        memberOf: 'UN',
    },
    ST: {
        name: 'Sao Tome and Principe',
        native: 'São Tomé e Príncipe',
        phone: [239],
        continent: 'AF',
        capital: 'São Tomé',
        currency: ['STN'],
        languages: ['pt'],
        memberOf: 'UN',
    },
    SV: {
        name: 'El Salvador',
        native: 'El Salvador',
        phone: [503],
        continent: 'NA',
        capital: 'San Salvador',
        currency: ['SVC', 'USD'],
        languages: ['es'],
        memberOf: 'UN',
    },
    SX: {
        name: 'Sint Maarten',
        native: 'Sint Maarten',
        phone: [1721],
        continent: 'NA',
        capital: 'Philipsburg',
        currency: ['ANG'],
        languages: ['nl', 'en'],
        memberOf: 'NL',
    },
    SY: {
        name: 'Syria',
        native: 'سوريا',
        phone: [963],
        continent: 'AS',
        capital: 'Damascus',
        currency: ['SYP'],
        languages: ['ar'],
        memberOf: 'UN',
    },
    SZ: {
        name: 'Eswatini',
        native: 'Eswatini',
        phone: [268],
        continent: 'AF',
        capital: 'Lobamba',
        currency: ['SZL'],
        languages: ['en', 'ss'],
        memberOf: 'UN',
    },
    TC: {
        name: 'Turks and Caicos Islands',
        native: 'Turks and Caicos Islands',
        phone: [1649],
        continent: 'NA',
        capital: 'Cockburn Town',
        currency: ['USD'],
        languages: ['en'],
        memberOf: 'GB',
    },
    TD: {
        name: 'Chad',
        native: 'Tchad',
        phone: [235],
        continent: 'AF',
        capital: "N'Djamena",
        currency: ['XAF'],
        languages: ['fr', 'ar'],
        memberOf: 'UN',
    },
    TF: {
        name: 'French Southern Territories',
        native: 'Territoire des Terres australes et antarctiques fr',
        phone: [262],
        continent: 'AN',
        capital: 'Port-aux-Français',
        currency: ['EUR'],
        languages: ['fr'],
        memberOf: 'FR',
    },
    TG: {
        name: 'Togo',
        native: 'Togo',
        phone: [228],
        continent: 'AF',
        capital: 'Lomé',
        currency: ['XOF'],
        languages: ['fr'],
        memberOf: 'UN',
    },
    TH: {
        name: 'Thailand',
        native: 'ประเทศไทย',
        phone: [66],
        continent: 'AS',
        capital: 'Bangkok',
        currency: ['THB'],
        languages: ['th'],
        memberOf: 'UN',
    },
    TJ: {
        name: 'Tajikistan',
        native: 'Тоҷикистон',
        phone: [992],
        continent: 'AS',
        capital: 'Dushanbe',
        currency: ['TJS'],
        languages: ['tg', 'ru'],
        memberOf: 'UN',
    },
    TK: {
        name: 'Tokelau',
        native: 'Tokelau',
        phone: [690],
        continent: 'OC',
        capital: 'Fakaofo',
        currency: ['NZD'],
        languages: ['en'],
        memberOf: 'NZ',
    },
    TL: {
        name: 'East Timor',
        native: 'Timor-Leste',
        phone: [670],
        continent: 'OC',
        capital: 'Dili',
        currency: ['USD'],
        languages: ['pt'],
        memberOf: 'UN',
    },
    TM: {
        name: 'Turkmenistan',
        native: 'Türkmenistan',
        phone: [993],
        continent: 'AS',
        capital: 'Ashgabat',
        currency: ['TMT'],
        languages: ['tk', 'ru'],
        memberOf: 'UN',
    },
    TN: {
        name: 'Tunisia',
        native: 'تونس',
        phone: [216],
        continent: 'AF',
        capital: 'Tunis',
        currency: ['TND'],
        languages: ['ar'],
        memberOf: 'UN',
    },
    TO: {
        name: 'Tonga',
        native: 'Tonga',
        phone: [676],
        continent: 'OC',
        capital: "Nuku'alofa",
        currency: ['TOP'],
        languages: ['en', 'to'],
        memberOf: 'UN',
    },
    TR: {
        name: 'Turkey',
        native: 'Türkiye',
        phone: [90],
        continent: 'AS',
        continents: ['AS', 'EU'],
        capital: 'Ankara',
        currency: ['TRY'],
        languages: ['tr'],
        memberOf: 'UN',
    },
    TT: {
        name: 'Trinidad and Tobago',
        native: 'Trinidad and Tobago',
        phone: [1868],
        continent: 'NA',
        capital: 'Port of Spain',
        currency: ['TTD'],
        languages: ['en'],
        memberOf: 'UN',
    },
    TV: {
        name: 'Tuvalu',
        native: 'Tuvalu',
        phone: [688],
        continent: 'OC',
        capital: 'Funafuti',
        currency: ['AUD'],
        languages: ['en'],
        memberOf: 'UN',
    },
    TW: {
        name: 'Taiwan',
        native: '臺灣',
        phone: [886],
        continent: 'AS',
        capital: 'Taipei',
        currency: ['TWD'],
        languages: ['zh'],
    },
    TZ: {
        name: 'Tanzania',
        native: 'Tanzania',
        phone: [255],
        continent: 'AF',
        capital: 'Dodoma',
        currency: ['TZS'],
        languages: ['sw', 'en'],
        memberOf: 'UN',
    },
    UA: {
        name: 'Ukraine',
        native: 'Україна',
        phone: [380],
        continent: 'EU',
        capital: 'Kyiv',
        currency: ['UAH'],
        languages: ['uk'],
        memberOf: 'UN',
    },
    UG: {
        name: 'Uganda',
        native: 'Uganda',
        phone: [256],
        continent: 'AF',
        capital: 'Kampala',
        currency: ['UGX'],
        languages: ['en', 'sw'],
        memberOf: 'UN',
    },
    UM: {
        name: 'U.S. Minor Outlying Islands',
        native: 'United States Minor Outlying Islands',
        phone: [1],
        continent: 'OC',
        capital: '',
        currency: ['USD'],
        languages: ['en'],
        memberOf: 'US',
    },
    US: {
        name: 'United States',
        native: 'United States',
        phone: [1],
        continent: 'NA',
        capital: 'Washington D.C.',
        currency: ['USD', 'USN', 'USS'],
        languages: ['en'],
        memberOf: 'UN',
    },
    UY: {
        name: 'Uruguay',
        native: 'Uruguay',
        phone: [598],
        continent: 'SA',
        capital: 'Montevideo',
        currency: ['UYI', 'UYU'],
        languages: ['es'],
        memberOf: 'UN',
    },
    UZ: {
        name: 'Uzbekistan',
        native: "O'zbekiston",
        phone: [998],
        continent: 'AS',
        capital: 'Tashkent',
        currency: ['UZS'],
        languages: ['uz', 'ru'],
        memberOf: 'UN',
    },
    VA: {
        name: 'Vatican City',
        native: 'Vaticano',
        phone: [379],
        continent: 'EU',
        capital: 'Vatican City',
        currency: ['EUR'],
        languages: ['it', 'la'],
    },
    VC: {
        name: 'Saint Vincent and the Grenadines',
        native: 'Saint Vincent and the Grenadines',
        phone: [1784],
        continent: 'NA',
        capital: 'Kingstown',
        currency: ['XCD'],
        languages: ['en'],
        memberOf: 'UN',
    },
    VE: {
        name: 'Venezuela',
        native: 'Venezuela',
        phone: [58],
        continent: 'SA',
        capital: 'Caracas',
        currency: ['VES'],
        languages: ['es'],
        memberOf: 'UN',
    },
    VG: {
        name: 'British Virgin Islands',
        native: 'British Virgin Islands',
        phone: [1284],
        continent: 'NA',
        capital: 'Road Town',
        currency: ['USD'],
        languages: ['en'],
        memberOf: 'GB',
    },
    VI: {
        name: 'U.S. Virgin Islands',
        native: 'United States Virgin Islands',
        phone: [1340],
        continent: 'NA',
        capital: 'Charlotte Amalie',
        currency: ['USD'],
        languages: ['en'],
        memberOf: 'US',
    },
    VN: {
        name: 'Vietnam',
        native: 'Việt Nam',
        phone: [84],
        continent: 'AS',
        capital: 'Hanoi',
        currency: ['VND'],
        languages: ['vi'],
        memberOf: 'UN',
    },
    VU: {
        name: 'Vanuatu',
        native: 'Vanuatu',
        phone: [678],
        continent: 'OC',
        capital: 'Port Vila',
        currency: ['VUV'],
        languages: ['bi', 'en', 'fr'],
        memberOf: 'UN',
    },
    WF: {
        name: 'Wallis and Futuna',
        native: 'Wallis et Futuna',
        phone: [681],
        continent: 'OC',
        capital: 'Mata-Utu',
        currency: ['XPF'],
        languages: ['fr'],
        memberOf: 'FR',
    },
    WS: {
        name: 'Samoa',
        native: 'Samoa',
        phone: [685],
        continent: 'OC',
        capital: 'Apia',
        currency: ['WST'],
        languages: ['sm', 'en'],
        memberOf: 'UN',
    },
    XK: {
        name: 'Kosovo',
        native: 'Republika e Kosovës',
        phone: [377, 381, 383, 386],
        continent: 'EU',
        capital: 'Pristina',
        currency: ['EUR'],
        languages: ['sq', 'sr'],
    },
    YE: {
        name: 'Yemen',
        native: 'اليَمَن',
        phone: [967],
        continent: 'AS',
        capital: "Sana'a",
        currency: ['YER'],
        languages: ['ar'],
        memberOf: 'UN',
    },
    YT: {
        name: 'Mayotte',
        native: 'Mayotte',
        phone: [262],
        continent: 'AF',
        capital: 'Mamoudzou',
        currency: ['EUR'],
        languages: ['fr'],
        memberOf: 'FR',
    },
    ZA: {
        name: 'South Africa',
        native: 'South Africa',
        phone: [27],
        continent: 'AF',
        capital: 'Pretoria',
        currency: ['ZAR'],
        languages: ['af', 'en', 'nr', 'st', 'ss', 'tn', 'ts', 've', 'xh', 'zu'],
        memberOf: 'UN',
    },
    ZM: {
        name: 'Zambia',
        native: 'Zambia',
        phone: [260],
        continent: 'AF',
        capital: 'Lusaka',
        currency: ['ZMW'],
        languages: ['en'],
        memberOf: 'UN',
    },
    ZW: {
        name: 'Zimbabwe',
        native: 'Zimbabwe',
        phone: [263],
        continent: 'AF',
        capital: 'Harare',
        currency: ['USD', 'ZAR', 'BWP', 'GBP', 'AUD', 'CNY', 'INR', 'JPY'],
        languages: ['en', 'sn', 'nd'],
        memberOf: 'UN',
    },
};

export const countryCodes: string[] = Object.keys(countries);
export const countryCodesInUN: string[] = countryCodes.filter((code) => countries[code].memberOf === 'UN');
