export const quotes = [
    ['The man who smiles when things go wrong has thought of someone to blame it on.'],
    [
        "It's true that we don't know what we've got until we lose it, but it's also true that we don't know what we've been missing until it arrives.",
    ],
    ['Never take life seriously. Nobody gets out alive anyway.'],
    ['The average woman would rather have beauty than brains, because the average man can see better than he can think.'],
    ['There are no stupid questions, just stupid people.'],
    ['When I die, I want to go peacefully like my Grandfather did, in his sleep – not screaming, like the passengers in his car.'],
    ['Behind every successful man is a surprised woman.'],
    [
        "Son, if you really want something in this life, you have to work for it. Now quiet! They're about to announce the lottery numbers.",
        'Homer Simpson',
    ],
    ['Last night I lay in bed looking up at the stars in the sky and I thought to myself, where the heck is the ceiling.'],
    ["You tried your best and you failed miserably. The lesson is 'never try'.", 'Homer Simpson'],
    ["Everyone is entitled to their own opinion. It's just that yours is stupid."],
    ["Marriage is give and take. You'd better give it to her or she'll take it anyway.", 'Joey Adams'],
    ["I have opinions of my own – strong opinions – but I don't always agree with them.", 'George Bush'],
    [
        "When you are courting a nice girl an hour seems like a second. When you sit on a red-hot cinder a second seems like an hour. That's relativity.",
        'Albert Einstein',
    ],
    ['Duct tape is like the force. It has a light side, a dark side, and it holds the world together.'],
    ["He who laughs last didn't get it."],
    ["No, please don't eat me. I have a wife and kids, eat them.", 'Homer Simpson'],
    [
        'When one person suffers from a delusion it is called insanity; when many people suffer from a delusion it is called religion.',
        'Robert Pirsig',
    ],
    ["Only two things are infinite, the universe and human stupidity, and I'm not sure about the former.", 'Albert Einstein'],
    ['A lie gets halfway around the world before the truth has a chance to get its pants on.', 'Sir Winston Churchill'],
    ["I hope I didn't brain my damage...", 'Homer Simpson'],
    ["Do, or do not. There is no 'try'.", 'Yoda'],
    [
        'C makes it easy to shoot yourself in the foot; C++ makes it harder, but when you do, it blows away your whole leg.',
        'Bjarne Stroustrup',
    ],
    ["I have not failed. I've just found 10,000 ways that won't work.", 'Thomas Alva Edison'],
    ['There is no reason anyone would want a computer in their home.', 'Ken Olson, founder of Digital Equipment Corp., 1977'],
    ['Who the hell wants to hear actors talk?', 'H. M. Warner, founder of Warner Brothers, 1927'],
    ['Everything that can be invented has been invented.', 'Charles H. Duell, U.S. Office of Patents, 1899'],
    ['God gave men both a penis and a brain, but unfortunately not enough blood supply to run both at the same time.', 'Robin Williams'],
    ['We are not retreating – we are advancing in another direction.', 'General Douglas MacArthur'],
    ["I handed in a script last year and the studio didn't change one word. The word they didn't change was on page 87.", 'Steve Martin'],
    ['I believe there would be many people alive today if there were a death penalty.', 'Nancy Reagan'],
    ['Behind every great man is a woman rolling her eyes.', 'Jim Carrey'],
    [
        'America will never be destroyed from the outside. If we falter and lose our freedoms, it will be because we destroyed ourselves.',
        'Abraham Lincoln',
    ],
    ['Better to remain silent and be thought a fool than to speak out and remove all doubt.', 'Abraham Lincoln'],
    [
        "What counts is not necessarily the size of the dog in the fight – it's the size of the fight in the dog.",
        'General Dwight D. Eisenhower',
    ],
    ['Always remember that you are absolutely unique. Just like everyone else.', 'Margaret Mead'],
    ["If you love something, set it free. Unless it's a tiger.", 'Phil Dunphy'],
    ['No man has a good enough memory to be a successful liar.', 'Abraham Lincoln'],
    ['People who think they know everything are a great annoyance to those of us who do.', 'Isaac Asimov'],
    ["Roses are red, violets are blue, I'm schizophrenic, and so am I.", 'Oscar Levant'],
    ['Life is hard. After all, it kills you.', 'Katharine Hepburn'],
    ['I can resist everything except temptation.', 'Oscar Wilde'],
    ["If women ran the world we wouldn't have wars, just intense negotiations every 28 days.", 'Robin Williams'],
    ['All generalizations are false, including this one.', 'Mark Twain'],
    ['The secret of business is to know something that nobody else knows.'],
    ["If you can't convince them, confuse them.", 'Harry S Truman'],
    ['Engineering is achieving function while avoiding failure.', 'Henry Petroski'],
    ['Software is a great combination between artistry and engineering.', 'Bill Gates'],
    ['Engineers like to solve problems. If there are no problems handily available, they will create their own problems.', 'Scott Adams'],
    ['Debugging is like being the detective in a crime movie where you are also the murderer.', 'Filipe Fortes'],
    [
        'Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.',
        'Martin Golding',
    ],
    [
        "CSS is easy. It's like riding a bike, which is on fire and the ground is on fire and everything is on fire because it is hell.",
        '@iamdevloper',
    ],
    ['Weeks of programming can save you hours of planning.'],
    ['🎵 99 little bugs in the code. 99 little bugs. Take one down, patch it around. 127 little bugs in the code... 🎵'],
];
